# -*- coding: utf-8 -*-
"""ML_5_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3KJlv4ohdVNIuOAk29QnDum7JMJYOWL
"""

from google.colab import files

!unzip "Experiment 5_Dataset-20260207T042443Z-1-001.zip"

!ls

!ls "Experiment 5_Dataset/Experiment_5 dataset"

import pandas as pd
data = pd.read_csv("Experiment 5_Dataset/Experiment_5 dataset/english.csv")
data.head()

import cv2
import numpy as np
base_path = "Experiment 5_Dataset/Experiment_5 dataset/"
images = []
labels = []
for i in range(len(data)):
    img_path = base_path + data.iloc[i, 0]
    label = data.iloc[i, 1]
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print("Image not found:", img_path)
        continue
    img = cv2.resize(img, (28, 28))
    img = img.flatten() / 255.0
    images.append(img)
    labels.append(label)
X = np.array(images)
y = np.array(labels)
print("X shape:", X.shape)
print("y shape:", y.shape)

"""# PLA"""

# Split Dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print("Training samples:", X_train.shape)
print("Testing samples:", X_test.shape)

import numpy as np

class PerceptronScratch:
    def __init__(self, learning_rate=0.01, epochs=50):
        self.lr = learning_rate
        self.epochs = epochs

    # activation function
    #   y^=1 if z>=0
    #   else 0 if z<0

    def step_function(self, x):
        return 1 if x >= 0 else 0


    # training function
    def fit(self, X, y):
        n_samples, n_features = X.shape

        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.epochs):
            # one sample at a time.
            for i in range(n_samples):
                # z= w.x+b (weighted sum)
                linear_output = np.dot(X[i], self.weights) + self.bias
                y_pred = self.step_function(linear_output)
                # η(y−y^​)
                update = self.lr * (y[i] - y_pred)
                # w=w+η(y−y^​)x
                self.weights += update * X[i]
                # b=b+η(y−y^​)
                self.bias += update

    def predict(self, X):
        predictions = []
        for x in X:
            # z=w⋅x+b
            linear_output = np.dot(x, self.weights) + self.bias
            predictions.append(self.step_function(linear_output))
        return np.array(predictions)

class MultiClassPLA:
    def __init__(self, learning_rate=0.01, epochs=50):
        self.lr = learning_rate
        self.epochs = epochs
        self.models = {}

    def fit(self, X, y):
        # y=['0','1','2',...,'Z','a','b',...,'z'] 62 classes
        self.classes = np.unique(y)
        for cls in self.classes:
            print("Training class:", cls)

            # if cls='A'
            # all 'A' labels=1
            # all other labels=0 this is one vs reset
            binary_y = np.where(y == cls, 1, 0)

            #Creating one binary perceptron.
            model = PerceptronScratch(self.lr, self.epochs)
            #Train a binary perceptron for current class against all other classes.
            model.fit(X, binary_y)
            #Save the trained model in dictionary.
            self.models[cls] = model

    def predict(self, X):
        scores = []

        for cls in self.classes:
            model = self.models[cls]
            # z=w⋅x+b
            linear_output = np.dot(X, model.weights) + model.bias
            scores.append(linear_output)

        scores = np.array(scores)
        return self.classes[np.argmax(scores, axis=0)]

pla_model = MultiClassPLA(learning_rate=0.01, epochs=10)

pla_model.fit(X_train, y_train)

y_pred = pla_model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report

print("PLA Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""# MLP"""

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

mlp = MLPClassifier(
    hidden_layer_sizes=(256,128),
    # f(x)=max(0,x) for relu
    activation='relu',
    solver='adam',
    learning_rate_init=0.001,
    batch_size=64,
    # epochs = more epochs then model can train more
    max_iter=200,
    random_state=42
)

mlp.fit(X_train, y_train)

y_pred_mlp = mlp.predict(X_test)

print("MLP Accuracy:", accuracy_score(y_test, y_pred_mlp))
print(classification_report(y_test, y_pred_mlp))

"""# Hyperparameter tuning

### Configuration 1
"""

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

mlp = MLPClassifier(
    hidden_layer_sizes=(128,),
    # f(x)=max(0,x) for relu
    activation='relu',
    solver='sgd',
    learning_rate_init=0.01,
    batch_size=32,
    # epochs = more epochs then model can train more
    max_iter=200,
    random_state=42
)

mlp.fit(X_train, y_train)

y_pred_mlp = mlp.predict(X_test)

print("MLP Accuracy:", accuracy_score(y_test, y_pred_mlp))
print(classification_report(y_test, y_pred_mlp))

"""### Configuration 2

"""

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

mlp = MLPClassifier(
    hidden_layer_sizes=(256,128),
    # f(x)=max(0,x) for relu
    activation='relu',
    solver='adam',
    learning_rate_init=0.001,
    batch_size=64,
    max_iter=200,
    random_state=42
)

mlp.fit(X_train, y_train)

y_pred_mlp = mlp.predict(X_test)

print("MLP Accuracy:", accuracy_score(y_test, y_pred_mlp))
print(classification_report(y_test, y_pred_mlp))

"""### Configuration 3"""

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

mlp = MLPClassifier(
    hidden_layer_sizes=(512,256,128),
    activation='tanh',
    solver='adam',
    learning_rate_init=0.0005,
    batch_size=64,
    max_iter=200,
    random_state=42
)

mlp.fit(X_train, y_train)

y_pred_mlp = mlp.predict(X_test)

print("MLP Accuracy:", accuracy_score(y_test, y_pred_mlp))
print(classification_report(y_test, y_pred_mlp))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import numpy as np

cm = confusion_matrix(y_test, y_pred_mlp)

print("Confusion Matrix Shape:", cm.shape)

labels = sorted(np.unique(y_test))

plt.figure(figsize=(6,5))
plt.imshow(cm)
plt.title("Confusion Matrix - MLP (Test Data)")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.xticks(range(len(labels)), labels, rotation=90)
plt.yticks(range(len(labels)), labels)

plt.colorbar()
plt.show()









